### ISSUE TITLE
Add links to related resources

### ISSUE THREAD

**Issue by jsnmrs** [double-great/listen#8]
https://www.powermapper.com/tests/ is the most substantial.

**Comment by jsnmrs** [comment]
@katydecorah I started on this, but I'm unsure how to structure. Could "related resources" be a data file that gets looped at the bottom of the `home` layout? If so, this is the data structure I'm imagining:

```
links:
  - title: PowerMapper Assistive technology compatibility tests
    description: An extensive library of screen reader tests 
    url: https://www.powermapper.com/tests/
```

Displayed as `- [{{title}}]({{url}}) — {{description}}`

Could you point me in the right direction, or if you're game, grab this one completely?
